- name: remove selinux
  yum: name=selinux state=absent

- name: disable selinux
  command: setenforce 0

- name: ensure port 80 is opened
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: ensure port 443 is opened
  firewalld:
    service: https
    permanent: true
    state: enabled

- name: restart firewalld
  service: name=firewalld state=restarted

- name: ensure epel is installed
  yum: name=epel-release state=latest

- name: install required packages
  yum: name={{ item }} state=latest
  with_items:
   - haproxy
   - certbot
   - git
   - python34
   - python34-pip
   - python34-devel
   - curl-devel
   - gcc

- name: ensure haproxy is enabled and running
  service: name=haproxy state=started enabled=true

- name: ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/ssl/haproxy
    - /var/run/haproxy/

- name: copy default ssl cert
  copy:
    src: ../files/default.pem
    dest: /etc/ssl/cert.pem

- name: copy marathon-lb.service
  template:
    src: ../templates/marathon-lb.service
    dest: /etc/systemd/system/marathon-lb.service

- name: copy EnvVars file
  copy:
    src: ../files/EnvVars
    dest: /opt/haproxy_automatron.env

- name: clone marathon-lb
  git:
    repo: 'https://github.com/mesosphere/marathon-lb.git'
    dest: /opt/marathon-lb
    update: no
    force: yes

- name: clone haproxy_automatron
  git:
    repo: 'https://github.com/volfco/haproxy_automatron.git'
    dest: /opt/haproxy_automatron
    update: yes
    force: yes

- name: set haproxy_automatron.py as an executable
  command: chmod +x /opt/haproxy_automatron/haproxy_automatron.py

- name: generate template softlinks
  file:
    src: "/opt/haproxy_automatron/marathon-lb-templates/{{ item }}"
    dest: "/opt/marathon-lb/templates"
    state: link
    force: yes
  with_items:
    - HAPROXY_FRONTEND_HEAD
    - HAPROXY_HTTP_FRONTEND_HEAD
    - HAPROXY_HTTP_FRONTEND_HEAD
    - HAPROXY_HEAD

- name: execute pip install
  command: pip3 install -r requirements.txt
  args:
    chdir: /opt/marathon-lb/
  environment: 
    PYCURL_SSL_LIBRARY: nss # CentOS 7.2

- name: make sure lets encrypt is configured to auto renew
  cron:
    name: "certbot"
    special_time: daily
    job: "/opt/haproxy_automatron/haproxy_automatron.py;"

# TODO Enable Marathon-LB service
